# 만들어야할 것
#  - serverport 설정
#  - spring application 이름 설정
#  - datasource 이름, 비밀번호, url 설정
#  - jpa hibernate ddl- auto 설정
#  - jpa properties dialect : postgresql 설정
#  - show sql 설정
#
#    eureka server 생성 이후)
#  - eureka server url 설정, fetch-registry, register with eureka true 설정


server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    username: park
    password: 1234
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
